### ISSUE TITLE
Spinner freezes while a page is loading.

### ISSUE THREAD

**Issue by banesa00** [fgnass/spin.js#106]
Hi!!!

I was trying to use this spinner as a loading status indicator for loading content in a div but unfortunately I'm facing the exact same issue that I was facing when using a rotating gif image. I'm placing the spinner in a separate div and not the one where the content(with a lot of javascript) is being loaded using the jquery load() method. Despite that the spinner stops when the content is loading and then starts rotating again once the page has been loaded in the div. This defeats the basic purpose of using a loading spinner, right? Any suggestions or ideas as to how this could be overcome would be highly appreciated.I have tried all sorts of things starting from using a gif as a background-image for the div showing the loading status, using setInterval() to reset the image after every 100 ms, using setTimeout() to reset the image, but nothing has worked so far. I came across spin.js the other day and after reading the wonderful reviews about this I was really hopeful that at least this would work. But unfortunately that didn't happen. This spinner looks really nice and I'd be more than happy if I could get this to work as a loading status indicator.

Thanks,
Sayak

**Comment by Rudresh-Ajgaonkar** [comment]
I am facing the same issue. Is there any solution yet?

**Comment by theodorejb** [comment]
Please reopen with a reproducible example if this is still an issue in spin.js v3.0.

**Comment by ximet** [comment]
I have the same problem. For example: I run your demo and after in console write infinity cycle.

**Comment by theodorejb** [comment]
I'm not sure how you expect it to work if it's blocked by an infinite loop. Do you have any suggestions?

**Comment by ximet** [comment]
@theodorejb Yes, I think you may use css spinner for example this demo: http://tobiasahlin.com/spinkit/. If I use the same infinity cycle, I don't have any problem with spinner

**Comment by theodorejb** [comment]
@ximet That demo doesn't support IE 9, though, and the animation rules are hard-coded (in spin.js they are configurable via JavaScript). Previous versions of spin.js used keyframe animations in modern browsers, but in order to do so it had to inject a new stylesheet into the DOM, which violated strict CSP (issue #115).

Maybe in the next major version we could drop IE 9 support, but we'd still need a way to support strict CSP.
