### ISSUE TITLE
'Spinner is not defined' when injected into certain pages

### ISSUE THREAD

**Issue by craic** [fgnass/spin.js#111]
I have a JS script that is injected into arbitrary web pages from a bookmarklet. When a user double clicks a word it triggers an ajax call to my server with that word. 

I'm using spin.js to display the spinner while the call is processed. 

On some pages it works great - but on others - e.g. http://www.bbc.co.uk/news/ - I get 'Uncaught ReferenceError: Spinner is not defined' in reference to this line in your jquery plugin

``` javascript
      data.spinner = new Spinner($.extend({color: $this.css('color')}, opts)).spin(this);
```

The BBC site has a LOT of other scripts so I assume there is some conflict here. The problem occurs whether the spin.js is minified or not and whether the code in in a separate file or in my js file.

Any ideas on how to debug this or to isolate the spin.js code ?

**Comment by UsgsMonkey** [comment]
Greetings,

I'm rather new to the world of modules and dependency injection and am currently working an implementation using CommonJS where I appear to be running into the same problem described above with Spin.js.  Is there a comparable example implementation using CommonJS or guidance you can provide on how to construct a module implementing Spin.js within an application?

**Comment by UsgsMonkey** [comment]
Nevermind.  I figured it out finally through trial-and-error...

```
var Spinner = require('spin.js');
var pSpinner = new Spinner().spin(document.body);
```
