### ISSUE TITLE
[Problem] spin.js doesn't work with strict CSP

### ISSUE THREAD

**Issue by ctemplin** [fgnass/spin.js#115]
Hello,
We're tightening up our content-security-policy as much as possible. We'd like to use "style-src 'self';" but this breaks spin.js in at least a couple places:
1. Line 30 if arguments[i].nodeName == "STYLE"
2. Line 40 where a new stylesheet is injected into the DOM

For our other code, we've had to migrate all of our inline styles to use css classes instead. Could spin.js be modified to optionally use this behavior and thereby support a strict CSP?

Thanks very much for the great script! I hope we can continue to use it with our high-security site.

**Comment by xandaro** [comment]
+1. This is the only reason preventing us from using spin.js

**Comment by joaoritter** [comment]
+1

**Comment by dcc635** [comment]
+1
