### ISSUE TITLE
Flickering if applied to opacity:0.5 element in Chrome v25

### ISSUE THREAD

**Issue by mherodev** [fgnass/spin.js#128]
I like it when my loading elements fade out a little and spin, but for some reason that no longer works in Chrome. I've now replaced spin.js with a janky gif until I have more time to hack at why this is happening. 

As for research, I looked into a solution from the past related to using hardware acceleration (the transform3d flag), but removing that didn't solve the issue. 

Michael

**Comment by theodorejb** [comment]
Please reopen this issue if it is still a problem in spin.js v3.0.
