### ISSUE TITLE
ReferenceError: 'Spinner is not defined' Using RequireJS

### ISSUE THREAD

**Issue by Bart-Holland** [fgnass/spin.js#131]
I use RequireJS to load spin.js:

require.config({
    paths: {
        jquery: 'jquery-1.9.0',
        json2: 'json2',
        handlebars: 'handlebars',
        spin: 'spin',
        login: 'login'
    }
});

And than load it like this:

require(['jquery','spin', 'json2', 'handlebars'], function() {
    //do some stuff

```
require(['login'], function() {
   //no scripts
});
```

});

when in the login.js I set the spinner:
var spinTarget = document.getElementById('login_spin');
var spinThis = new Spinner(spinnerOpts).spin();

I will see in this in the console:
ReferenceError: 'Spinner is not defined' 

I tried this solution you offered: 
https://github.com/hull/spin.js/commit/d2e39d1015cfbe2e6d51dbc194a8d0fcada9b7f7

But this did not make a difference.

**Comment by taruntelang** [comment]
I would like to stop this spinner in a different module. How can I do this ?
