### ISSUE TITLE
jQuery stop() not working?

### ISSUE THREAD

**Issue by n8felton** [fgnass/spin.js#139]
It appears that a recent commit may have broke the stop() function?

Basic test: http://jsfiddle.net/n8felton/MJZJa/

**Comment by drfunk2458** [comment]
I can't seem to stop your spinner either...  Here is my code...
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
    <head>
        <title>Spin Test</title>
        <script type="text/javascript" src="/APM2/js/jquery-1.12.4.js"></script>
        <script type="text/javascript" src="/APM2/js/spin.js"></script>
        <script type="text/javascript" src="/APM2/js/jquery.spin.js"></script>
        <script type="text/javascript"">
 
          $(document).ready(function () {
                var opts = {
                  lines: 12 // The number of lines to draw
                , length: 14 // The length of each line
                , width: 6 // The line thickness
                , radius: 16 // The radius of the inner circle
                , scale: 1 // Scales overall size of the spinner
                , corners: 1 // Corner roundness (0..1)
                , color: '#000' // #rgb or #rrggbb or array of colors
                , opacity: 0.25 // Opacity of the lines
                , rotate: 0 // The rotation offset
                , direction: 1 // 1: clockwise, -1: counterclockwise
                , speed: 1 // Rounds per second
                , trail: 60 // Afterglow percentage
                , fps: 20 // Frames per second when using setTimeout() as a fallback for CSS
                , zIndex: 2e9 // The z-index (defaults to 2000000000)
                , className: 'spinner' // The CSS class to assign to the spinner
                , top: '50%' // Top position relative to parent
                , left: '50%' // Left position relative to parent
                , shadow: false // Whether to render a shadow
                , hwaccel: false // Whether to use hardware acceleration
                , position: 'absolute' // Element positioning
                }
                var target = document.getElementById('spinner')
                var spinner = new Spinner(opts).spin(target);
         });
        </script>
 
    </head>
    <body>
      <div id="spinner"></div>
     //do something important here..............
      <script type=\"text/javascript\"> $('#spinner').spin('hide'); </script>
    </body>
</html>
