### ISSUE TITLE
Scale animation freezes the window

### ISSUE THREAD

**Issue by olivierbeaulieu** [fgnass/spin.js#146]
I apply a -webkit-transform:scale property on the spinner element, along with a transition.

When I try to remove the spinner from the DOM, it freezes the browser window. I've never seen anything like it.

If I remove the transition on the transform property, everything works well.

Any thoughts? Seen this on the latest version of Chrome.

**Comment by theodorejb** [comment]
Please reopen with a reproducible example if this is still a problem with the latest version of spin.js.
