### ISSUE TITLE
Crash: unable to get property "style"

### ISSUE THREAD

**Issue by mbcooper** [fgnass/spin.js#151]
Here is the deal ....
I create a new div in JS and append it to the DOM.  It has no defined height or width or content.

I attach the spinner and ...

Unhandled exception at line 1, column 3482 in http://localhost:25000/Scripts/ThirdParty/spin.js

0x800a138f - Microsoft JScript runtime error: Unable to get value of the property 'style': object is null or undefined

**Comment by TimothyGu** [comment]
This is probably fixed a long time ago. If you still encounter this issue please provide a stand-alone test case.
