### ISSUE TITLE
Feature request - spin.js with modal view

### ISSUE THREAD

**Issue by ekloc** [fgnass/spin.js#163]
Is it possible to have spin.js overlay target element in modal view.  By that I mean, have main div with class="spinner" completely overlay target element (have height and width of target element).

**Comment by fprosper** [comment]
Hi, I know this is closed, old and outside the scope of spin.js development, but I can't see the spinner showing in both http://jsfiddle.net/8Mcr6/1/ or http://jsfiddle.net/8Mcr6/2. If you have the chance, could you tell me whether it's just me, or there is something wrong there? I would really to implement that solution. Thank you in advance.

**Comment by iappwebdev** [comment]
You included an outdated script source, you're getting network errors on both fiddles. See http://jsfiddle.net/8Mcr6/186/ and http://jsfiddle.net/8Mcr6/185/ for working examples.

**Comment by fprosper** [comment]
That's great thanks!
