### ISSUE TITLE
Show spinner at center of screen

### ISSUE THREAD

**Issue by shazdeh** [fgnass/spin.js#17]
I want to show the spinner at the middle of screen and not at the center of other elements. When I use the body but it creates scrollbars.
How could I do that?

**Comment by mrded** [comment]
You can do it this way:

    <div style="text-align: center;">
      <div class="mdl-spinner mdl-js-spinner is-active" style="margin: 20px;"></div>
    </div>

**Comment by Gennady-G** [comment]
> Create a DIV and center it on the screen manually. Then use this DIV as target:
> 
> <body>
>   <div id ="center" style="position:fixed;top:50%;left:50%"></div>
>   <script>
>     new Spinner().spin(document.getElementById('center'));
>   </script> 
> </body>

Thank You much **fgnass!**

Best regards,     
Gennady

**Comment by MrCsabaToth** [comment]
All someone needs is to specify `position: 'fixed'` along with `50vh` top and `50vw` left alignment settings if you want the spinner to be always at center and not being able to scrolled away.
