### ISSUE TITLE
Does not work in IE8

### ISSUE THREAD

**Issue by rexcfnghk** [fgnass/spin.js#172]
I am using Spin.js 1.3.2 and it seems the VML fallback does not work for IE8. My code for dynamically adding a `spinner` inside a jQuery `dialog`:

``` javascript
(function ($) {
    $(function() {
        var $loadingDialog = $("#loading-dialog").dialog(settings.loadingDialogSettings),
            spinner = new Spinner({
                top: "10px",
                left: "10px"
            });

        $.ajaxSetup({
            cache: false
        });

        $(document).ajaxStart(function() {
            spinner.spin($loadingDialog[0]);
            $loadingDialog.dialog("open");
        }).ajaxStop(function() {
            spinner.stop();
            $loadingDialog.dialog("close");
        });
    });
}(jQuery));
```

From the debugging window, I can see the `initVML()` function being called. However nothing is created inside the jQuery dialog (content `<div>` has no children).

On other browsers, the `spinner` is rendered perfectly without problems.

**Comment by theodorejb** [comment]
Closing since IE 8 is no longer supported anyway.
