### ISSUE TITLE
Only in Chrome: Causes parent divs to disappear when drawn in relatively positioned divs

### ISSUE THREAD

**Issue by stevensacks** [fgnass/spin.js#173]
Whenever I add spin to a relatively positioned div (for example, when I'm drawing a list of items without using li tags), it causes multiple parent divs to disappear. This only happens in Chrome.

This bug is reproducible every single time and appears to have started in a recent build of Chrome. I have tweeted at you about it multiple times and no answer so I made an issue here.

I need help figuring out why this is happening because entire parts of my UI are disappearing whenever I use spin to show something is loading.

**Comment by boustanihani** [comment]
having same issue here :(

Making the outer container statically positioned does not seem to solve the problem...

**Comment by theodorejb** [comment]
If this is still a problem with the latest version of spin.js and Chrome, please open a new issue.
