### ISSUE TITLE
Inverse Rotation

### ISSUE THREAD

**Issue by AaronOpfer** [fgnass/spin.js#174]
This is definitely a very minor feature request: It would be really awesome to have the option of making the entire spinner slowly rotate in the opposite direction of the spinner. The effort would probably be the most cool looking on spinners with a low/odd number of lines.

Another idea I had was being able to have variable speed something like 0.5+sin(time), in order to have a pulsing effect.

**Comment by TimothyGu** [comment]
The `direction` option is designed for this. As for variable speed, it might be possible to use a cubic-bezier. That would be fun :)
