### ISSUE TITLE
Animation flickering

### ISSUE THREAD

**Issue by mfrye** [fgnass/spin.js#182]
I'm using Chromium 28 and I'm trying to use this within an AngularJS app (RC 1.2). It seems to flicker once on every cycle though - it isn't a smooth animation. 

Has anybody else experienced this? I don't know if this is the latest version of Chromium issue, or if it's something that is potentially conflicting with Angular.

**Comment by TimothyGu** [comment]
If anybody can provide a standalone example I will take a look at it.
