### ISSUE TITLE
spin.js does not work in IE 8

### ISSUE THREAD

**Issue by hflaisher** [fgnass/spin.js#186]
Hello All:

I have seen 1-2 issues on this, but no answer.  On the spin.js website, I see only a small white rectangle inside the big black square where the spinner usually resides.  I have tried diff compat modes, quirks, etc.  no diff. 

would anyone have an answer to this?

thank you
Harvey

**Comment by theodorejb** [comment]
Closing since IE 6/7/8 are no longer supported.
