### ISSUE TITLE
Problem with AMD?

### ISSUE THREAD

**Issue by MTyson** [fgnass/spin.js#191]
It looks like there may be a problem with the AMD factory.

I couldn't figure out why Spinner was undefined until I stared at the source and realized I was in a Dojo project and so AMD was available.

I forced spin.js to use root.Spinner and it works.

At the very least there appears to be a conflict between spin.js and Dojo.

Thanks for the great script.

**Comment by TimothyGu** [comment]
I'll reopen this if there are further debugging information.
