### ISSUE TITLE
Spin.js freezes when DOM is being manipulated in IE9

### ISSUE THREAD

**Issue by jmwolfe** [fgnass/spin.js#197]
The docs seem to indicate that hwaccel: true should push the animation onto the graphics hardware and out of the main UI thread, thus permitting the animation to continue while the page DOM is being manipulated.

And this works well for Chrome. Unfortunately, it does NOT work for IE9. It does animate while a form is being processed (one IE issue) but following an AJAX request or other dynamic changes to the page (such as when angular-spinner is used in an AngularJS application), the icon freezes and it becomes no better than a lame animated gif from 1999.

**Comment by theodorejb** [comment]
If this is still a problem in spin.js v3.0, please reopen the issue with a reproducible example.
