### ISSUE TITLE
In IE11, element at 0 degrees doesn't animate after first rotation

### ISSUE THREAD

**Issue by jbmonroe** [fgnass/spin.js#198]
Subject pretty much says it all.  All the other browsers I check don't show the issue.

**Comment by a-v-l** [comment]
Same issue. Config was as following:
```js
opts = {
    lines: 9,
    length: 0,
    width: 4,
    radius: 7,
    corners: 1,
    color: '#006faa',
    opacity: 0
},
```
I use the spinner inside a button.

Screenshot:
![spinner](https://user-images.githubusercontent.com/3359867/30739056-6382ce2c-9f8c-11e7-8995-0fb1edb6a523.jpg)

**Comment by theodorejb** [comment]
This should be fixed in spin.js v3.0.
