### ISSUE TITLE
Spinner freezes on form submit (Opera 12)

### ISSUE THREAD

**Issue by moraug** [fgnass/spin.js#201]
Found this library in one of the answers here: http://stackoverflow.com/questions/780560/animated-gif-in-ie-stopping

Works fine in every browser that I need to support, but in Opera 12 still freezes on form submit.

**Comment by theodorejb** [comment]
Opera 12 is no longer a supported browser. If you are still having issues in the latest version of Opera, please file a new issue with steps to reproduce.
