### ISSUE TITLE
Enable export of CSS/Markup so spin.js can be a dev-only dependency

### ISSUE THREAD

**Issue by trullock** [fgnass/spin.js#203]
Would be nice to have a node task that given a spin configuration, it outputs the necessary markup and css, so this can be baked in to projects instead of being built dynamically at runtime (with performance unfriendly synchronous DOM/CSSOM I/O)

**Comment by theodorejb** [comment]
This is an interesting idea, but I'm not actually sure it would help performance. If you have a single-page app that uses many spinners, it would likely slow things down to have to load all the DOM/CSS for them even when they aren't being used.
