### ISSUE TITLE
Update NuGet package

### ISSUE THREAD

**Issue by hikalkan** [fgnass/spin.js#209]
Hi,

Can you share spin.js on nuget with the LATEST VERSION. The last update is 2013-05-05 on github: http://www.nuget.org/packages/Spin.js/

If you do not add, I can add it. But it would be better to update existing nuget package, instead of a new one.

Thanks.

**Comment by TimothyGu** [comment]
Unfortunately the nuget package is published by an unknown third party (@itmeze I believe). I'll contact him about this issue, and let's see what we can do.

**Comment by theodorejb** [comment]
Closing since the NuGet package is published by a third party and is not officially supported.
