### ISSUE TITLE
odd chrome issue, does not match demo page

### ISSUE THREAD

**Issue by tablatronix** [fgnass/spin.js#220]
I made a fiddle, same settings on my fiddle do not match the example page.
provided a link there as well to the example. I even compared the output code and didnt catch anything different.

http://jsfiddle.net/LdGFG/

It is as if transform translate is 1 px off, but its not, just renders as if.

baffled

**Comment by TimothyGu** [comment]
Unfortunately I can't see the issue you are describing here on my Windows 8.1 Chrome 43.0.2357.81 installation. #221 doesn't seem to make a difference either. Closing this and #221 unless there are further comments.

**Comment by tablatronix** [comment]
Yeah seems to have resolved now, I know several versions of chrome and canary had major rendering issues for a while as i kept an eye on it. Seems fine now.
