### ISSUE TITLE
No spinner in native IE8

### ISSUE THREAD

**Issue by ITBOE** [fgnass/spin.js#223]
The spinner is not showing up properly in IE8. It works fine in IE10 emulating IE8, but does not work in native IE8. There are no errors that I can see, but even the spin.js site shows only a black box with a white rectangle:

![image](https://cloud.githubusercontent.com/assets/7502286/2891886/083c24b4-d537-11e3-9dad-097c1235a047.png)

What can be done to make this work in native IE8? Thank you!

**Comment by TimothyGu** [comment]
See https://saucelabs.com/tests/c976894765e949db8dffa7be479e00ad

It works.
