### ISSUE TITLE
Not working in IE7/8 browser mode

### ISSUE THREAD

**Issue by sammydigits** [fgnass/spin.js#228]
The demo page (http://fgnass.github.io/spin.js/) is not showing a spinner in IE7/8 browser mode:

![ie7](https://cloud.githubusercontent.com/assets/1637993/2959030/f4ddc51c-daae-11e3-882e-597281f3b42a.JPG)

![ie8](https://cloud.githubusercontent.com/assets/1637993/2959035/fbcdcfac-daae-11e3-9d6e-37d9c3e736eb.JPG)

**Comment by TimothyGu** [comment]
Dup of #223.
