### ISSUE TITLE
blinking on chrome

### ISSUE THREAD

**Issue by iramtay** [fgnass/spin.js#231]
I noticed that the page will blink on Chome when the spinner is created.

Using v1.2.7 now, tried the latest version and it is still the same.

this is how i used it:

opts.length=0; opts.radius=1; opts.top='6px';
oblSpinner = new Spinner(opts).spin(document.getElementById("spinner-div"));
$("#spinner-div").css("display", "inline-table");

anyone else encountered the same issue?

**Comment by donhill** [comment]
This also happens on android, I am using jquerymobile 1.3.2 and phonegap 3.6 which probably uses chrome browser for the webview. I am using this for ajax calls 

$("#loading").spin(opts).hide();
$(document).ajaxStart(function(){ $('#loading').fadeIn(200); });
$(document).ajaxComplete(function(){ $('#loading').fadeOut(200); });

**Comment by TimothyGu** [comment]
Can someone post a full, standalone example?

I'll be reopening once someone comments.
