### ISSUE TITLE
"Mismatched anonymous define() module" exception when using require.min.js

### ISSUE THREAD

**Issue by pageorge** [fgnass/spin.js#239]
Line 11 in spin.js was causing the above exception after we upgraded to Kentico 8.0.18 which we think uses a newer version of require.min.js:

  /* AMD module */
  else if (typeof define == 'function' && define.amd) define(factory)

We removed line 11 from spin.min.js:
!function(a,b){"object"==typeof exports?module.exports=b():<DELETED_AMD_CODE_FROM_HERE>a.Spinner=b()}...

And job done! No more exception and spinner seems to work fine for us in most browsers. Not sure what the knock-on affect will be or if you are able to fix it.

**Comment by TimothyGu** [comment]
I don't think this is our problem. http://requirejs.org/docs/errors.html#mismatch says:

> To avoid the error:
>
> - Be sure to load all scripts that call define() via the RequireJS API. Do not manually code script tags in HTML to load scripts that have define() calls in them.
> - If you manually code an HTML script tag, be sure it only includes named modules, and that an anonymous module that will have the same name as one of the modules in that file is not loaded.
> - If the problem is the use of loader plugins or anonymous modules but the RequireJS optimizer is not used for file bundling, use the RequireJS optimizer.
> - If the problem is the var define lint approach, use `/*global define */` (no space before "global") comment style instead.
