### ISSUE TITLE
Disabling Background

### ISSUE THREAD

**Issue by serjooo** [fgnass/spin.js#254]
Hello, I would like to ask if there is anyway I can make the spinner load like a modal and disable everything in the background? Thank you for your time.

**Comment by dhoeric** [comment]
Instead of adding a feature on the package, this example may helps you.
http://jsfiddle.net/fgnass/EKWbw/

**Comment by TimothyGu** [comment]
spin.js generates a spinner. I think that while a modal would be helpful, it should not be in the core. I'll try to make an example that will be checked into the repo, for this feature.

**Comment by code-smith** [comment]
a much better and practical use case

**Comment by jegjessing** [comment]
Hmm no updates on this? I really would like this feature

**Comment by Viky-zhang** [comment]
+1

**Comment by theodorejb** [comment]
I agree that this would be a handy feature, but it shouldn't be part of the core library. Feel free to implement your own wrapper library offering this functionality.
