### ISSUE TITLE
no spin safari forms

### ISSUE THREAD

**Issue by ccfontes** [fgnass/spin.js#265]
Spinner doesn't spin in form submissions, but spins elsewhere in Safari. A similar issue was reported [here](http://stackoverflow.com/questions/21195994/safari-7-0-1-and-onsubmit) but remains without solution. I'm using Safari 7.0.5.

Any workaround possible?

**Comment by TimothyGu** [comment]
The SO post has an answer. Comment here if you still are having issues.
