### ISSUE TITLE
Right hand-side line never changes on IE 10/11

### ISSUE THREAD

**Issue by GerardFR** [fgnass/spin.js#272]
The line that is on the right hand-side (at 3 o'clock) never changes (stays at the same color all the time) on IE 10 or 11. It works fine on IE 9, Chrome or Firefox.

![1-2-2015 5-24-35 pm](https://cloud.githubusercontent.com/assets/8985347/5597549/84a43a0c-92a4-11e4-9718-effd07a38d32.png)

**Comment by TimothyGu** [comment]
Dup of #264.
