### ISSUE TITLE
How to change what's being animated?

### ISSUE THREAD

**Issue by slocs** [fgnass/spin.js#273]
I'd like to have a spinning image (with background-image? for spinning frogs) or use stroke (such as stroke-linecap) to change shape of end of the bar and not just the border-radius - is it possible to customize spinner.js to do this?

**Comment by TimothyGu** [comment]
Unfortunately no, not at this moment. We are not using SVG to render it, but rather "primitive" `border-radius`. And we are not planning on changing this soon.
