### ISSUE TITLE
Bower version is behind

### ISSUE THREAD

**Issue by tablatronix** [fgnass/spin.js#278]
bower spin.js#*               mismatch Version declared in the json (2.0.1) is different than the resolved one (2.0.2)

**Comment by gokimax80** [comment]
Hi, do you fix that issue?

**Comment by fgnass** [comment]
I'm looking for a maintainter to help me stuff like this as I'm currently very busy with other OSS projects. Ping me if you're interested, any help would be highly appreciated!

**Comment by TimothyGu** [comment]
Hey @fgnass, I'd be happy to take over the maintainership of this package. It's true that I don't have any contributions here (yet), but I hate to see a popular package like this with > 7000 stars being neglected. Feel free to check out my GitHub profile and you can email me if you have any questions. Thanks!

**Comment by fgnass** [comment]
@TimothyGu awesome! I added you as collaborator to the repository.

**Comment by TimothyGu** [comment]
@fgnass Cool! I'll start cleaning everything up

**Comment by TimothyGu** [comment]
Bower works now:

```
timothy_gu@tgdo:~$ bower info spin.js
bower not-cached    git://github.com/fgnass/spin.js.git#*
bower resolve       git://github.com/fgnass/spin.js.git#*
bower download      https://github.com/fgnass/spin.js/archive/2.1.0.tar.gz
bower extract       spin.js#* archive.tar.gz
bower resolved      git://github.com/fgnass/spin.js.git#2.1.0

{
  name: 'spin.js',
  version: '2.1.0',
  main: 'spin.js',
  dependencies: {},
  readme: 'README.md',
  repository: {
    type: 'git',
    url: 'git://github.com/fgnass/spin.js.git'
  },
  ignore: [
    'Gruntfile.js',
    'site',
    'bower.json',
    'component.json',
    'package.json'
  ],
  homepage: 'https://github.com/fgnass/spin.js'
}

Available versions:
  - 2.1.0
  - 2.0.2
  - 2.0.1
  - 2.0.0
  - 1.3.3
  - 1.3.2
  - 1.3.1
  - 1.3.0
  - 1.2.8
```
