### ISSUE TITLE
Animated Border Around Canvas

### ISSUE THREAD

**Issue by henrydavid100** [fgnass/spin.js#281]
Hello, I am trying to create a rainbow border for my program. However, I cannot seem to integrate my paint rectangles onto the program. Here is my code:

![1](https://cloud.githubusercontent.com/assets/11463790/6643563/98dd894a-c983-11e4-9018-7d8a0b9d2c08.png)
![2](https://cloud.githubusercontent.com/assets/11463790/6643564/98df03b0-c983-11e4-9694-6eba0af1335f.png)

**Comment by DaAwesomeP** [comment]
Would you mind copying/pasting your code (or parts of it) into the issue? It's a lot easier to read, alter, and test that way. You can encase it in Markdown Code Tags [as described here]()https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code-and-syntax-highlighting.

**Comment by TimothyGu** [comment]
Timeout. Closing.
