### ISSUE TITLE
Class with "visibility: hidden" on container breaks the spinner

### ISSUE THREAD

**Issue by max-tubecorporate** [fgnass/spin.js#284]
Test case: http://jsfiddle.net/z17x20hp/

Click on "Hide spinner" twice to see the problem.

**Comment by c0r3yz** [comment]
Update your code to start the spinner when you are toggling the spinner's visibility:

    document.getElementById('hide_spinner').onclick = function(){
        container.className = container.className == '' ? 'hidden' : '';
        spinner.spin(target);
    };

**Comment by max-tubecorporate** [comment]
Thank you.
