### ISSUE TITLE
Stop spin after sometime . 

### ISSUE THREAD

**Issue by ajain27** [fgnass/spin.js#290]
Hi, I have just started using this spinner control as I am working on an angular project. Now according to the plunker i need to have a stop spinner button in order to stop it. Is there a way I can stop the spinner control as soon as my ajax call is complete. 

Example -> I make a post -> start a spinner . But then when that post request is completed I want to stop that spinner automatically. 

Here is what I am trying to do. 

```
HTML - Button ng-click-"myfunction(); startSpin()"

Controller -   $scope.startSpin = ->
    usSpinnerService.spin 'spinner-1' 

  $scope.stopSpin = ->
    usSpinnerService.stop 'spinner-1' 

myfunction() { 
     myService.postRequestFunc().then ->
             //Post is made 
      }

Sevice - My $http.post(".................").then (response) ->
     //Code 
```

At the same time I would also like to add some text below the spinner... 
Like - "Adding.....", "Deleting.....", "Updating......"

How can we do that as well ?

Ankit

**Comment by TimothyGu** [comment]
You can use the `.stop()` API to stop spinning. Changing text is not related to spin.js.
