### ISSUE TITLE
Tag v2.1.0

### ISSUE THREAD

**Issue by theodorejb** [fgnass/spin.js#291]
According to http://fgnass.github.io/spin.js/ the current version is 2.1.0 (released 2015-04-16). However, this release hasn't been tagged yet in the Git repository.

**Comment by fgnass** [comment]
Thanks, fixed it!

**Comment by bhaktisukhadiya** [comment]
Is this version is CSP compatible or not? 
  I am importing the spin.min.js V2.0.1 library file in my AngularJS with C# application. The problem arises when I add the following CSP line to my project:

<add name="Content-Security-Policy" value="script-src 'self' http: https: 'unsafe-inline' `'unsafe-eval';"/>`
<add name="Content-Security-Policy" value="script-src 'self' http: https: 'unsafe-inline' 'unsafe-eval';"/>

I need to remove unsafe-eval from the policy. Therefore, I need to check whether the library file is CSP compatible or not, specifically checking if setTimeout, is used without causing errors in the console.
