### ISSUE TITLE
[1.3.3] Spinner is not centered correctly

### ISSUE THREAD

**Issue by PhuongXmaster** [fgnass/spin.js#293]
If the parent container is 
- position: relative;
- has border;

The spinner will be mis-aligned some pixels because pos() doesn't count container border.

The bug is clearly visible if the border is think or the container is narrow.
![thick border](https://cloud.githubusercontent.com/assets/12637590/7877167/d96b0578-0619-11e5-846c-97430c50201c.png)
![small container](https://cloud.githubusercontent.com/assets/12637590/7877219/b25fbd74-061a-11e5-8624-6b1076b98ea6.png)

This bug doesn't appear from 2.0.0 onwards because spin.js center by 50% of relative parent. This requires the container must be position to relative. 

Solution: update the pos function to count clientLeft and clientTop:
o.x+=el.offsetLeft+el.clientLeft, o.y+=el.offsetTop+el.clientTop

**Comment by TimothyGu** [comment]
This bug is the exact bug we fixed in 2.0.0: https://github.com/fgnass/spin.js/blob/master/site/index.html#L185-L188

> The Spinner is now absolutely positioned at top: 50% left: 50% by default.

**Comment by PhuongXmaster** [comment]
@TimothyGu I'm aware that since 2.0.0, spinner is positioned absolutely in center. However, it requires the container to be positioned relative. This breaks many places in our customer code, not just our code. We're not ready for this upgrade yet.

This is the fix that targets to 1.3.x only.

**Comment by TimothyGu** [comment]
Thank you for this explanation, and I totally understand your frustration. It is kind of late to submit a patch for a branch that is basically closed (or never exists) more than a year ago however.

However, there is another thing that precludes me from just branching off a 1.x. Semantic version specifies that any behavior change would need a major bump. This is not possible anymore as we already have a 2.0. [Who knows](http://xkcd.com/1172/) who's going to depend on this behavior?

So, sadly, it is not possible for me to make another release now. If the patch works for you, good! It might help other people, whom I honestly hope to not be a large population ;)
