### ISSUE TITLE
Possible to add composer.json for Composer support

### ISSUE THREAD

**Issue by frontalnugity** [fgnass/spin.js#297]
I'd be great if I could include this in my projects via Composer - I think a composer.son file just needs to be described and added to the project.

**Comment by TimothyGu** [comment]
A pull request would surely be welcome for this.

**Comment by fgnass** [comment]
I'm sorry, but this won't happen for the same reason we don't provide Ruby gems, Python PIP packages or Maven files. If you want to manage frontend dependencies in your PHP project please use npm or bower.

**Comment by fgnass** [comment]
This looks like a viable solution too: https://github.com/composer/composer/issues/524#issuecomment-4912681

**Comment by frontalnugity** [comment]
No worries - I would be happy for everything to be referenced and synced without hooking up them the front-end portion of code.

I'll look at the link as well - looks promising.  My understanding was all that was necessary was to add the json file with a few properties and that would be sufficient - but I'm still unsure of the full requirements and support overhead if any.

Thanks anyways!
