### ISSUE TITLE
Error: b.insertBefore is not a function

### ISSUE THREAD

**Issue by ReneMuetti** [fgnass/spin.js#302]
Hello

We use a Magento shop in version 1.9. in this we would like to use the spinner. Unfortunately, this is absolutely impossible, because jQuery is running in Magento in the namespace $ j. The plugin is therefore without any function.

**Comment by RussNelson** [comment]
Is this the same as #305?

**Comment by ReneMuetti** [comment]
I can not say exactly...
More likely is that the plugin is not fully developed as a module.
Then kan such behavior occur.

**Comment by theodorejb** [comment]
Closing since the jQuery plugin has been removed in spin.js v3.0.
