### ISSUE TITLE
Ability to pause the spinner without removing it

### ISSUE THREAD

**Issue by heaven** [fgnass/spin.js#303]
I have slides on the page, they switch with animation. Adding spin.js slows those down. Actually not just slows, they stop working at all. I need an ability to pause spinners before call "animate" on the slides switch and run it again after animation is done.

**Comment by theodorejb** [comment]
Using spin.js v4 you can accomplish this yourself with a few lines of code. Add the following rule to your CSS file:

```css
.paused > div > div {
    animation-play-state: paused !important;
}
```

Then the paused state can be togged like this in your JavaScript/TypeScript code (where `spinner` is an instance of the `Spinner` class):

```javascript
spinner.el.classList.toggle('paused');
```
