### ISSUE TITLE
Use `position: static`

### ISSUE THREAD

**Issue by mazing** [fgnass/spin.js#307]
Isn't it possible to use the spinner with `position: static`?

I cannot use it as absolutely positioned and I cannot find any options to change it.

**Comment by fgnass** [comment]
The position has to be `absolute`, `fixed` or `relative` since the child elements (the lines) are absolutely positioned. Wouldn't `{ position: 'relative' }` work too in your case?

**Comment by mazing** [comment]
yes, position: relative would probably work as well. how can I set it to relative?

**Comment by fgnass** [comment]
It's a config option.

Martin <notifications@github.com> schrieb am Fr., 13. Nov. 2015 um 15:21:

**Comment by mazing** [comment]
Sorry. Just found it in https://github.com/fgnass/spin.js/blob/master/spin.js. Thanks
