### ISSUE TITLE
I do not work spin.js

### ISSUE THREAD

**Issue by JuanVqz** [fgnass/spin.js#308]
Hi good day. I'm trying to use spin does not work me.
Clone the project and put it in the folder htdocs between examples and do not run. somebody help me? Thank you!

**Comment by TimothyGu** [comment]
Unfortunately I don't understand this question. What are the "examples" you are referring to?

---

Desafortunadamente no comprendo este pregunta. ¿Qué son los «ejemplos»?

Y, se habla español :)

**Comment by JuanVqz** [comment]
gracias TimothyGU los ejemplos que vienen cuando se clona el spin, ya lo hice en css gracias.

**Comment by TimothyGu** [comment]
Ah, los archivos en `site/`? Tienes que copiar los scripts al `site/`. Puedes usar `grunt`:

```sh
npm i -g grunt-cli # instalar grunt. es posible que tienes que usar `sudo` para este
npm i              # instalar los dependientes locales para grunt
grunt
```

Ahora debes poder abrir `site/index.html` :)

**Comment by JuanVqz** [comment]
gracias TimothyGu!! muy amable
