### ISSUE TITLE
No Animation on iOS Safari

### ISSUE THREAD

**Issue by flowip** [fgnass/spin.js#309]
Here is a simple example: http://jsfiddle.net/eyh1uytj/2/
1) Click "Show Spinner" link.
2) Press "Home Button" on your mobile device
3) Open Safari again
4) Click "Show Spinner" link and see that animation no longer works

I'm really surprised that I'm the first who submitted this issue. You may replace steps 2 and 3 with just navigation to another browser tab, and then navigate back.

Tested on iOS 9.1.

**Comment by gkrizek** [comment]
I'm experiencing this as well. Seems to happen randomly.

**Comment by gkrizek** [comment]
I used this issue to get a work around in place:
https://github.com/fgnass/spin.js/issues/262

**Comment by flowip** [comment]
I've posted my fix/workaround as a pull request.

**Comment by theodorejb** [comment]
This should be fixed in spin.js v3.0.
