### ISSUE TITLE
Scale not working correctly in IE8

### ISSUE THREAD

**Issue by Drumstix42** [fgnass/spin.js#315]
In IE8, the the "Scale" option is not working correctly (VML). It ends up slightly rotating each bar when you scale it. The default scale of "1" works as expected.

You can test this by visiting [http://fgnass.github.io/spin.js/](http://fgnass.github.io/spin.js/) on an IE8 VM.

The problem seems to exist @ line 305:
`, s = o.scale * 2 * r`

Changing it to not include scale for "s" seems to fix the problem:
`, s = 2 * r`

**Comment by theodorejb** [comment]
Closing since IE8 is no longer supported.
