### ISSUE TITLE
Spinner no longer works for https connections

### ISSUE THREAD

**Issue by kerrermanisNL** [fgnass/spin.js#321]
When trying to load the following over https:

```
<script src="//fgnass.github.io/spin.js/spin.min.js"></script>
```

The following error will be returned:

```
Blocked loading mixed active content
```

I think this has to do with the redirection to `js.org` which gets loaded over http, and not https.

When trying to load the `js.org` script over https:

```
<script src="//spin.js.org/spin.min.js"></script>
```

It won't show the error, but it won't load the content either. This is because the certificate is not meant for `js.org`, but only the following domains:
- www.github.com, 
- *.github.com, 
- github.com, 
- *.github.io, 
- github.io, 
- *.githubusercontent.com, 
- githubusercontent.com 

This means I'm not able to load the spinner over any https connection.

**Comment by Jimadine** [comment]
Yes the SSL certificate is broken. From Chrome Devtools:

> Certificate Error
> There are issues with the site's certificate chain (net::ERR_CERT_COMMON_NAME_INVALID).

Quick fix for me was use a CDN e.g. https://cdnjs.cloudflare.com/ajax/libs/spin.js/2.3.2/spin.min.js

**Comment by theodorejb** [comment]
Closing since the script isn't meant to be directly loaded from spin.js.org. It is recommended to install from npm instead, and use a module bundler to create your production build.
