### ISSUE TITLE
Problem when used Inside jquery dialog

### ISSUE THREAD

**Issue by augustwind** [fgnass/spin.js#322]
I'm using a Jquery UI dialog, in which I'm using spin.js which works perfectly.
No matter whether or not I have closeOnEscape set to true or false with the dialog, When the ESCAPE key is pressed, the spinner stops spinning and hangs all further jquery or .NET processing.
BTW - this is used in an ASP.Net 4.0 webforms application

**Comment by Jimmy-Ji** [comment]
dasf

**Comment by theodorejb** [comment]
Please reopen with a reproducible example if this is still an issue with spin.js v3.0.
