### ISSUE TITLE
I can't get code straight off of spin.js.org to work

### ISSUE THREAD

**Issue by OHCSupport** [fgnass/spin.js#324]
I created [a bare bones fiddle](https://jsfiddle.net/5gwzt8Lj/8/) with code straight off of spin.js.org. As you can see, no spinner is created. What am I doing wrong?

**Comment by TimothyGu** [comment]
Check your browser console:

```
Uncaught ReferenceError: Spinner is not defined
    at (index):84
```

The `<script>` tags in the HTML box of the fiddle is executed before the JavaScript box, so Spinner isn't defined when HTML `<script>` tags are executed.
