### ISSUE TITLE
Z-index and position

### ISSUE THREAD

**Issue by lencioni** [fgnass/spin.js#34]
It would be nice to be able to set some more options, like z-index or position within the element.

In my implementation, the spinner is getting hidden undereneath some elements. Or, on long pages, the spinner appears below the current viewport.

Alternatively, for the position, it would be nice if it would be vertically centered in the viewable portion of the element instead of the viewable+nonviewable portion of the element. Does that make sense? And, maybe it would make sense to set a high z-index by default?

**Comment by jbetances** [comment]
Is there a way to both have the spinner going and at the same time be able click at other elements within the page?
