### ISSUE TITLE
Spinner is not defined Angular2+

### ISSUE THREAD

**Issue by rdcm** [fgnass/spin.js#340]
I'am trying use spin.js with typings in my app, but when i try create spinner instance, my componnet throw exception:

`ReferenceError: Spinner is not defined`

Spin.js imported in componnet like this `import "spin.js";`

`"spin.js": "2.3.2",`
`"@types/spin": "2.3.30",`

Code in component:

```
import {Component, AfterViewInit} from "@angular/core";
import "spin.js";

@Component({
    selector: 'loader',
    templateUrl: 'loader.html'
})
export class LoaderComponent implements AfterViewInit{
    ngAfterViewInit(): void {
        this._spinner = new Spinner({color:'#85266c', lines: 12});
    }

    private _spinner: Spinner;
}
```

What i'am doing wrong?

**Comment by ivanjaros** [comment]
I have the same issue, seems this is the cause, still, https://github.com/fgnass/spin.js/issues/323
