### ISSUE TITLE
Spinner not working since 10 nov 2017

### ISSUE THREAD

**Issue by AMaar786** [fgnass/spin.js#344]
I'm getting the following error on the console.

Uncaught SyntaxError: Unexpected token export
Incident:1654 Uncaught ReferenceError: Spinner is not defined

Please help as we are using SpinJs in production.

Thanks,
Shahrukh

**Comment by KooYH** [comment]
me too.
http://fgnass.github.io/spin.js/spin.min.js

this link is broken

**Comment by AMaar786** [comment]
yes I already copied the code locally and then did that change, worked for me too. Thanks!

**Comment by xsynaptic** [comment]
Check the release notes and #343; the project was upgraded to ES6. I'm guessing you should probably stick with the version 2 branch if you're not transpiling your code and bundling modules with Babel/Webpack.

**Comment by theodorejb** [comment]
I updated the website to clarify that spin.js shouldn't be loaded from a `<script>` tag directly referencing the official website, as this is likely to break your app whenever a major new version is released.
