### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by yaddly** [fgnass/spin.js#352]
Good day, I have an error on line 114 ==> export { Spinner }; Again when I add this script to BundleConfig.cs it breaks existing scripts. May I request a working Sample done in Asp.net MVC

**Comment by frankenstein-uk** [comment]
Same problem for me, it breaks on export { Spinner };

**Comment by quakedc** [comment]
Have you tried commenting out that line?

**Comment by magicbruno** [comment]
Coomnting out the line worked for me.

**Comment by yaddly** [comment]
Thank you very much for the update on this issue

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by thehig** [comment]
Same as #356
