### ISSUE TITLE
Keeping the spinner in center whilst scrlling up/down

### ISSUE THREAD

**Issue by amitbhavsarGit** [fgnass/spin.js#354]
I am not reporting an issue rather I wanted to know if it is possible to keep the spinner in the middle of the page whilst scrolling up or down. Currently, its position is static and user loses its view if scrolling is required.

Please reply
Thanks and Regards

Amit

**Comment by theodorejb** [comment]
Yes, you could do this by setting the `position` option to `"fixed"`, or by placing the spinner inside an element with a fixed position.
