### ISSUE TITLE
Unexpected export 

### ISSUE THREAD

**Issue by holgersielaff** [fgnass/spin.js#356]
'Unexpected export' error at line 114 (npm 5.6.0)

Maybe export Spinner directly with 'export const'

**Comment by theodorejb** [comment]
What's giving you that error? Are you trying to load the file in a browser that doesn't support ES6 modules? You'll need to use a module bundler such as Webpack or Rollup for this to work.

**Comment by vikyd** [comment]
But how can I use spin.js V3 without Webpack or Rollup?

**Comment by thehig** [comment]
I'm having this same issue, (unexpected token export) although not with webpack which is working fine, but within my jest tests (scaffolded through create-react-app)

![image](https://user-images.githubusercontent.com/96122/38318034-581515a8-3826-11e8-8bb0-e4ac043527e7.png)

**Comment by tolu** [comment]
I'm having the same issue in my tests, using mocha with typescript (actually `ts-node`). The same issue will continue to be around (in node and ts-node) since even experimental module support requires the use of `*.mjs` file extensions at this time.

After some time spent reading up on the issue and the solutions it seems to me that it is premature to publish `esnext`/`mjs`/`esm` _only_...

This is from Rollup's readme
![image](https://user-images.githubusercontent.com/658586/40546131-a0c43a9c-602e-11e8-8e7b-a215b208c2c5.png)

That (adding a `module`-field to `package.json`) seems like a solution that would work for the issues reported here as well as the original case #341.

I'll try to get a PR going along those lines in the weekend.

**Comment by theodorejb** [comment]
@tolu More and more libraries are moving to ES6, though, and at some point your tests will have to work with these files. The way I currently work around the lack of Node/IE support is to use ES6 imports in my tests, and then create a test bundle file with Rollup before running it with Mocha.

**Comment by thehig** [comment]
This seems like an effective strategy to alienate users

**Comment by adonespitogo** [comment]
A browser-only library that needs nodejs package mechanism to in order to work. Great.

**Comment by tolu** [comment]
An updated recommendation now that modules are supported in all major browsers:

From: https://developers.google.com/web/fundamentals/primers/modules

> A note on file extensions
>You may have noticed we’re using the .mjs file extension for modules. On the Web, the file extension doesn’t really matter, as long as the file is served with the JavaScript MIME type text/javascript. The browser knows it’s a module because of the type attribute on the script element.

> Still, we recommend using the .mjs extension for modules, for two reasons:

> 1. During development, it makes it crystal clear that the file is a module as opposed to a regular script. (It’s not always possible to tell just by looking at the code.) As mentioned before, modules are treated differently than regular scripts, so the difference is hugely important!
> 2. It’s consistent with Node.js, where the experimental modules implementation only supports files with the .mjs extension.

**Comment by kgeographer** [comment]
I am trying to use this in a Django app, with no ES6 or webpack. I cannot simply load spin.js the same way I load a dozen other packages, as the export command is invalid. The website statement "No dependencies" is not true, and I won't ever get back the hour I spent learning that.

**Comment by theodorejb** [comment]
@kgeographer Did you read the website instructions? The **Bundling** paragraph says the following:

> If for some reason you can't use ES6 modules or a module bundler, download [spin.umd.js](https://spin.js.org/spin.umd.js) and save it in your repo.

**Comment by kgeographer** [comment]
I am ashamed to say I did not. For ES5, you I needed the full reference `var spinner = new Spin.Spinner().spin();` to get started, but otherwise good to go. Sorry for the bother.
