### ISSUE TITLE
^4.0.0  No animation

### ISSUE THREAD

**Issue by joeyer** [fgnass/spin.js#369]
No animation in Google Chrome 
There is no animation in Google Chrome, there is no animation in the 4.0.4 version installed. But I can install 2.3.0.

var opts = {
            lines: 13, // The number of lines to draw
            length: 38, // The length of each line
            width: 17, // The line thickness
            radius: 45, // The radius of the inner circle
            scale: 0.05, // Scales overall size of the spinner
            corners: 1, // Corner roundness (0..1)
            color: '#ffffff', // CSS color or array of colors
            speed: 1, // Rounds per second
            rotate: 0, // The rotation offset
            direction: 1, // 1: clockwise, -1: counterclockwise
          };
          
 this._spinner = new Spinner(opts).spin(this.refs.dot);

**Comment by theodorejb** [comment]
Did you load the spin.css stylesheet file?

**Comment by simplenotezy** [comment]
Yes I did. I have same error:

![image](https://user-images.githubusercontent.com/3786627/70534078-93dd9380-1b5a-11ea-8b15-8a740ee385cb.png)

Possibly related: https://github.com/fgnass/spin.js/issues/373

**Comment by theodorejb** [comment]
Is the spinner on a white background? If you use white lines on a white background you won't be able to see them.
