### ISSUE TITLE
No spin.min.js found for spin.js v4.0.0

### ISSUE THREAD

**Issue by gvdm90** [fgnass/spin.js#370]
Hello. I have an Angular 8.0.0 project in which I'm upgrading `spin.js` from version `^2.3.2` to `^4.0.0`. With version 2.3.2 the `npm install` command will download, with the full package, also the `spin.min.js` file which is then referenced in my `angular.js`.

Instead when I upgrade to version 4.0.0 no `spin.min.js` is included and the error below is thrown when running `ng serve`

> Error: ENOENT: no such file or directory, open 'C:\Project\node_modules\spin.js\spin.min.js'

Same issue with version 3.1.0. Is it a bug or an intended behaviour?

**Comment by theodorejb** [comment]
This is intended behavior. Instead of trying to manually include spin.min.js, simply import the `Spinner` class in your TypeScript code. The module should be minified as part of your production build process.
