### ISSUE TITLE
How do we change to font awesome spinner fa fa-spinner fa-spin?

### ISSUE THREAD

**Issue by ratheeshgh** [fgnass/spin.js#372]
We currently use this spin.js and css file as default spinner and customer requirement is to replace with the font awesome spinner. Please suggest changes to be done to incorporate font awesome spinner.

**Comment by theodorejb** [comment]
I'm not sure I understand the question. If you're wondering how to change the spinner styling to match a particular icon, try playing around with the settings at spin.js.org. I added a built-in `spinner-line-shrink` animation preset which may be what you need: https://spin.js.org/#?lines=8&length=0&width=20&radius=21&scale=1&corners=1&speed=1.2&rotate=0&animation=spinner-line-shrink&direction=1&color=%23ffffff&fadeColor=transparent&top=50&left=50&shadow=0%200%201px%20transparent.
