### ISSUE TITLE
Spin do not show animation in UI after updating Bootstrap and jQuery

### ISSUE THREAD

**Issue by LVDuong** [fgnass/spin.js#373]
I am using spin.min.js version 2.3.2. With old version of Bootstrap and jQuery, the spin animation show in the view when I use showLoading. But after I update my Bootstrap to version 4.3.1 and 3.4.1 with jQuery, the function showLoading() keep running but it do not show spin animation in the view.

Who can help me resolve this problem to show spin in the loading view? 

Thanks so much!

**Comment by simplenotezy** [comment]
I believe I have the same error. The spinner is visible and all HTML is there:

![image](https://user-images.githubusercontent.com/3786627/70533971-6db7f380-1b5a-11ea-8c2e-28b18eee1374.png)

But the animation is just simply black. No animation:

![image](https://user-images.githubusercontent.com/3786627/70534005-78728880-1b5a-11ea-950c-a20871e7b9b1.png)

**Comment by theodorejb** [comment]
v2.3.2 isn't supported anymore. I would recommend updating to v4 and adding back jQuery support if you need it per https://github.com/fgnass/spin.js/issues/365#issuecomment-547738650.
