### ISSUE TITLE
please make sure newest versions are CDNs.

### ISSUE THREAD

**Issue by gacallea** [fgnass/spin.js#374]
hi,

first things first: thanks for this great lib! so nimble and simple!

I would love to include it from cdnjs but it's stuck at version 2.3.2 . I don't want to use npm, only the <head> but CDNs have only the older version. I know this may be out of your control, but as the author would be nice to make sure CDNs are aligned with master releases.

please and thank you

**Comment by WingGithub** [comment]
+1

**Comment by lenamtl** [comment]
+1

**Comment by theodorejb** [comment]
I'm not sure how the old version got on cdnjs in the first place, nor do I know how to update it there.

**Comment by xtuc** [comment]
in https://github.com/cdnjs/cdnjs you can check the package configuration under `ajax/lib/NAME/package.json`, and based on https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md if that make sense. Also we know that updates via git has some issues, make sure to use update via npm.

**Comment by joe-oli** [comment]
Even if one does not want to use CDN and downloads js,css directly from the page https://spin.js.org/ the js script causes errors in the console; Please remove the line `export { Spinner };` from the webpage release !
I don't mean to be demanding, and I am grateful for the author's work, but it should work out of the box, without a hint that the developer has not tested their own library in CDN mode :-)

**Comment by theodorejb** [comment]
@joe-oli The website already had a link to the UMD module, but I updated it now to make it more prominent next to the ESM link.

**Comment by RobJohnston** [comment]
Projects on GitHub can be retrieved via the [jsDelivr](https://www.jsdelivr.com/?docs=gh) CDN.  For example, https://cdn.jsdelivr.net/gh/fgnass/spin.js@4.1.0/

This project is already on NPM, and anything in NPM is available via the [UNPKG](https://unpkg.com/) CDN.  For example, https://unpkg.com/browse/spin.js@4.1.0/

Or via [libman](https://github.com/aspnet/LibraryManager) for ASP.Net projects (selecting a sub-set of files):

``` json
{
  "provider": "unpkg",
  "library": "spin.js@4.1.0",
  "destination": "wwwroot/lib/spin-js/",
  "files": [
    "CHANGELOG.md",
    "LICENSE.md",
    "README.md",
    "spin.css",
    "spin.js" 
  ]
},
```

**Comment by PandaWood** [comment]
> @joe-oli The website already had a link to the UMD module

I think what @joe-oli is referring to, is even the latest version 4.1.1 eg via this [link](https://cdnjs.cloudflare.com/ajax/libs/spin.js/4.1.1/spin.min.js). Just including this in a browser, in plain vanilla javascript, immediately gives this error: `Unexpected token 'export' (at spin.min.js:1:2805) ?
