### ISSUE TITLE
Since I upgrade the script the spin does not stop anymore..

### ISSUE THREAD

**Issue by lenamtl** [fgnass/spin.js#375]
Hi,

How can I stop the spin?

It was working fine with old version
https://jsfiddle.net/lenamtl/gn7jqk45/

Now I'm trying to use it with newer version.
For the test I'm using file from https://spin.js.org/spin.umd.js
Can anyone tell me which version it is?
See my example
https://jsfiddle.net/lenamtl/fzdqtg2u/

I'm not using NPM, I don't want to install it for only one JS file... so  I just don't which version it is.

Thanks

**Comment by theodorejb** [comment]
The https://spin.js.org/spin.umd.js file is for the latest version. You should be able to stop the spinner using the `stop()` method, just as in previous versions. Make sure you're following all the instructions at https://spin.js.org/.

**Comment by lenamtl** [comment]
Hi,
Thanks for the info
Have you check my jsfiddle as stop is not working...
` spinner.stop(); `

any clue?

**Comment by theodorejb** [comment]
When starting the spinner you need to assign the instance to the `spinner` variable: https://jsfiddle.net/xbj95dv1/

**Comment by lenamtl** [comment]
Ho  I see, my bald
I forgot 	**spinner =** 
from `spinner = new Spin.Spinner(opts).spin(target); `

Thanks fo your time
