### ISSUE TITLE
IE 11 Spinner Not Showing

### ISSUE THREAD

**Issue by aquilaseye** [fgnass/spin.js#382]
I noticed that this spinner no longer works for IE 11. When I navigate to this website "https://spin.js.org/", the spinner does not show or animate. On the bottom of the page, "Internet Explorer 10+" is included in the list of supported browsers. Just wondering if it will still be supported since I have this weird user requirement to meet.

**Comment by aquilaseye** [comment]
![IESpinnerNotWorking](https://user-images.githubusercontent.com/28285620/99445809-f0047800-28d2-11eb-91d3-0be73f3d1fba.PNG)

**Comment by aquilaseye** [comment]
![IESpinnerNotWorking](https://user-images.githubusercontent.com/28285620/99445978-2a6e1500-28d3-11eb-887d-2425c4a73092.PNG)

**Comment by theodorejb** [comment]
@aquilaseye Thanks for reporting - this is fixed now. It wasn't an incompatibility with the library itself, but with the code for the website.
