### ISSUE TITLE
Need to change spinner color

### ISSUE THREAD

**Issue by laugirard** [fgnass/spin.js#383]
Hey guys, I'm using spin.js in one of my websites, and the client requested for the spinning wheel to have a different color rather than black. Which is the file I have to modify in order to achieve this?

The wheel appears after the "login" button is pressed on credentials land page (user/password input). I've tried adding bits of code here and there but am unable to change the color properly, could you give me any advice?

Thank you for your time.

**Comment by theodorejb** [comment]
You don't need to modify any spin.js file. Just set the `color` property when initializing the Spinner object. Please follow the example and instructions at https://spin.js.org/.
