### ISSUE TITLE
Is spin.min.js CSP compatible?

### ISSUE THREAD

**Issue by bhaktisukhadiya** [fgnass/spin.js#394]
I am importing the spin.min.js V2.0.1 library file in my AngularJS with C# application. The problem arises when I add the following CSP line to my project:

`<add name="Content-Security-Policy" value="script-src 'self' http: https: 'unsafe-inline' 'unsafe-eval';"/>`
  
I need to remove unsafe-eval from the policy. Therefore, I need to check whether the library file is CSP compatible or not, specifically checking if setTimeout, is used without causing errors in the console.

**Comment by theodorejb** [comment]
Version 2.x is very old and not supported. Can you try using the latest version?

**Comment by theodorejb** [comment]
Yes, the latest version of spin.js is CSP compatible.
