### ISSUE TITLE
Opacity option for background

### ISSUE THREAD

**Issue by dnagir** [fgnass/spin.js#50]
I am really missing the `backgroundOpacity: 0.7` option.

This would be veeery useful.

**Comment by vaibhavpandeyvpz** [comment]
+1 @nicooga, you are awesome :) your code did it simply & beautifully

**Comment by wanashi** [comment]
You can also do with pure javascript
(required IE10+ )

```
var spinner = new Spinner(opts).spin(target);
target.classList.add("opaque");

# Stop Spin
target.classList.remove("opaque");
spinner.stop()
```
https://developer.mozilla.org/en/docs/Web/API/Element/classList
