### ISSUE TITLE
Ability to have HTML/text below the spinner

### ISSUE THREAD

**Issue by raygig** [fgnass/spin.js#62]
It would be great if there was an option that allows for text/html that can be placed below the spinner. This would give the spinner some more context of whats it doing. ie. Loading Something... 

Ideally the width of the text would be calculated and would be placed below and centered relative to the spinner.

Because the spinner is placed absolutly I would think it would be the appropriate for this extra text/html go along for the ride.

**Comment by pythagoras1357** [comment]
I was able to do this by adding the css to the div I'm adding the spinner to:

#pageSpinner {
    width: 100%;
    height: 100%;
    background-color: rgba(0, 0, 0, .6);
    display: flex !important;
    align-items: center;
    justify-content: center;
    position: fixed;
    z-index: 1000;
    top: 0;
}

<div id="pageSpinner"><div id="page-spinner-copy">loading...</div></div>
