### ISSUE TITLE
Spin.js conflicting with 3D animations of jQTouch

### ISSUE THREAD

**Issue by kaleazy** [fgnass/spin.js#88]
I have a weird problem where the existence of Scroll.js (which is an awesome plugin, thank you!) is conflicting with the 3D animations in jQTouch. Seems like all the non-3D page transitions work fine (slideleft, slideright, slideup, etc), but none of the 3D animations are working (cubeleft, cuberight, etc). I'm using Zepto.js for this, here's my call order.

    <script type="text/javascript" src="js/zepto.min.js"></script>
    <script type="text/javascript" src="js/jqtouch.js"></script>
    <script type="text/javascript" src="js/spin.js"></script>

Any ideas what I should modify? Thanks in advance.

**Comment by TimothyGu** [comment]
If you are still having this problem, please provide a sample, standalone HTML file so that I can test and try to fix it. Thanks!
